version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  redis:
    image: redis:5.0.5-alpine
    restart: on-failure
    ports:
      - 6379:6379

  load-scale:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
      - prometheus
      - grafana
    environment:
      - NO_SUBSCRIBE=no-active
      - HOST_URL=https://chat.example.com
      - SSL_ENABLED=yes
      - REDIS_HOST=redis
      - TRY_REGISTER=no
      - HOW_MANY=100
      - SEATS_PER_ROOM=100
      - LOGIN_BATCH=20
      - SEND_MESSAGES=yes
      - MESSAGE_SENDING_RATE=0.0001
      - ROOM_ID=b4XgrgKajTXSqAsNW
      - OPEN_ROOM=no
      - LOGIN_OFFSET=671
      - CLIENT_TYPE=web
      - USERS_USERNAME=zz%s
      - USERS_PASSWORD=test1

  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3300:3000
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
